# Generated by Django 2.2.7 on 2019-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191129_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(height_field=400, null=True, upload_to='', width_field=600),
        ),
    ]
